Fix non-breaking space separator
meilisearch/Tokenizer pull request #44
Opened 2021-04-22 09:40 UTC by shekhirin

Resolves https://github.com/meilisearch/Tokenizer/issues/38

2021-04-28 06:37 UTC, LegendreM commented
Hello @shekhirin, welcome again 😃 , I think your PR can be merged like this.
However, I'm thinking about adding a new kind of separator (NonBreaking) which will be not indexed in the DB but will not split the word 🤔.
My approach will consider similar words, containing or not a non-breaking-separator, as the same word.
For example: 
- `SEG\u{00a0}WIC1` would be considered as the same word as `SEGWIC1`
- `испытательные` would be considered as the same word as  `испытателные`

do you think it's relevant to do it like this?

Thanks again for your contribution, enhancing the Cyrillic support in meilisearch! 🥇

2021-04-29 08:03 UTC, shekhirin commented
@LegendreM looks good to me. I've implemented the idea in the latest commit, could you check it please?

2021-04-29 09:44 UTC, LegendreM requested changes
Hello @shekhirin, I think you should roll back your last commit 😅, I was just asking a question and didn't request any changes.
Moreover, I don't know if adding a NonBreakingSeparator is the best solution to handle this, for example, we could remove non-breaking-separators during the normalization process.

2021-04-29 09:44 UTC, LegendreM commented on src/token_classifier.rs
> -        _ if ('\u{0410}'..='\u{044f}').contains(&c) => None, // russian cyrillic letters [а-яА-Я]
Why don't we support `Cyrillic letters [а-яА-Я]` anymore?

2021-04-29 13:52 UTC, shekhirin commented
@LegendreM ah ok. I thought you proposed a solution to implement 😬 
Reverted the last commit.

2021-05-03 06:16 UTC, LegendreM commented
Thank you for your contribution @shekhirin!

2021-05-03 06:16 UTC, merged